# Generated by Django 4.2.4 on 2023-09-13 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowverseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_class",
                    models.CharField(
                        choices=[
                            ("Forestcraft", "Forestcraft"),
                            ("Swordcraft", "Swordcraft"),
                            ("Runecraft", "Runecraft"),
                            ("Dragoncraft", "Dragoncraft"),
                            ("Shadowcraft", "Shadowcraft"),
                            ("Bloodcraft", "Bloodcraft"),
                            ("Havencraft", "Havencraft"),
                            ("Portalcraft", "Portalcraft"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("icon", models.ImageField(upload_to="class_icons/")),
            ],
        ),
        migrations.AddField(
            model_name="deck",
            name="expansion_cartas",
            field=models.CharField(default="Desconocida", max_length=100),
        ),
        migrations.AddField(
            model_name="deck",
            name="fecha_publicacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deck",
            name="formato_mazo",
            field=models.CharField(
                choices=[("Rotation", "Rotation"), ("Unlimited", "Unlimited")],
                default="Rotation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="wins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
