# Generated by Django 4.2.4 on 2023-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0002_shadowverseclass_deck_expansion_cartas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shadowverseclass",
            name="name_class",
            field=models.CharField(
                choices=[
                    ("forestcraft", "forestcraft"),
                    ("swordcraft", "swordcraft"),
                    ("runecraft", "runecraft"),
                    ("dragoncraft", "dragoncraft"),
                    ("shadowcraft", "shadowcraft"),
                    ("bloodcraft", "bloodcraft"),
                    ("havencraft", "havencraft"),
                    ("portalcraft", "portalcraft"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
