# Generated by Django 4.2.4 on 2023-09-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0003_alter_shadowverseclass_name_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shadowverseclass",
            name="name_class",
            field=models.CharField(
                choices=[
                    ("Forestcraft", "Forestcraft"),
                    ("Swordcraft", "Swordcraft"),
                    ("Runecraft", "Runecraft"),
                    ("Dragoncraft", "Dragoncraft"),
                    ("Shadowcraft", "Shadowcraft"),
                    ("Bloodcraft", "Bloodcraft"),
                    ("Havencraft", "Havencraft"),
                    ("Portalcraft", "Portalcraft"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
