# Generated by Django 4.2.4 on 2023-09-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0004_alter_shadowverseclass_name_class"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deck",
            old_name="formato_mazo",
            new_name="formato_deck",
        ),
        migrations.AddField(
            model_name="deck",
            name="clase_deck",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="decks.shadowverseclass",
            ),
        ),
    ]
