# Generated by Django 4.2.4 on 2023-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0005_rename_formato_mazo_deck_formato_deck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="imagen",
            field=models.ImageField(upload_to="decks/"),
        ),
    ]
