# Generated by Django 4.2.4 on 2023-09-27 17:44

import decks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0006_alter_deck_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="clase_deck",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deck",
            name="imagen",
            field=models.ImageField(upload_to=decks.models.custom_upload_to),
        ),
    ]
